name: Save multiple pages to Wayback machine

on: 
  
  schedule:
    # Replace "cron syntax" with a valid cron syntax
    # For example, to run the workflow every day at 12pm UTC, you would use "0 12 * * *"
    - cron: '45 12,13 * * *'

jobs:
  save-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install requests module
        run: |
          pip install requests
          
      - name: Create log directory and file
        run: |
          mkdir -p saving_logs
          touch saving_logs/log.csv
      - name: Save pages to Wayback machine
        env:
          ACCESS_KEY: ${{ secrets.WAYBACK_MACHINE__ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.WAYBACK_MACHINE__SECRET_KEY }}
          
        run: |
          python - <<EOF ${ACCESS_KEY} ${SECRET_KEY}
          
          import csv
          import requests
          import sys
          import time
          
          # Set the URLs of the web pages you want to save
          url_list = [
              'https://www.coronavirus.sachsen.de/infektionsfaelle-in-sachsen-4151.html',
              'https://www.bloomberg.com/billionaires/',
              'https://www.worldometers.info/coronavirus/',
              'https://www.bundesregierung.de/breg-de/themen/krieg-in-der-ukraine/lieferungen-ukraine-2054514',
              'https://www.rki.de/DE/Content/Infekt/Sentinel/Grippeweb/Wochenberichte/Wochenbericht_aktuell.html',
              'https://lua.rlp.de/de/corona-zahlen/',
              'https://www.bergfex.de/deutschland/schneewerte/',
              'https://www.bergfex.at/oesterreich/schneewerte/',
              'https://www.bergfex.ch/schweiz/schneewerte/',
              'https://www.bergfex.it/italien/schneewerte/',
              'https://www.bergfex.at/slovenia/schneewerte/',
              'https://www.bergfex.at/frankreich/schneewerte/',
              'https://www.bergfex.at/nederland/schneewerte/',              
              'https://www.bergfex.at/belgie/schneewerte/',
              'https://www.bergfex.at/polska/schneewerte/',
              'https://www.bergfex.at/czechia/schneewerte/',
              'https://www.bergfex.at/slovakia/schneewerte/',
              'https://www.bergfex.at/spanien/schneewerte/',              
              'https://www.bergfex.at/kroatien/schneewerte/',
              'https://www.bergfex.at/bosnien-herzegowina/schneewerte/',
              'https://www.bergfex.at/liechtenstein/schneewerte/'
          ]
          
          # Set the base URL of the Wayback Machine API
          api_base_url = 'https://web.archive.org/save'
          
          # Set the HTTP headers for the request
          headers = {
              'Authorization': f'LOW {sys.argv[0]}',
              'X-Amz-Secret-Key': sys.argv[1]
          }
          
          # Open a CSV file for writing the log information
          with open('saving_logs/log.csv', 'w', newline='') as csvfile:
              fieldnames = ['url', 'status']
              writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
              writer.writeheader()
              
              # Iterate through the pages and save each one to the Wayback machine
              for page in url_list:
                  # Make a POST request to the /save endpoint to save the page to the Wayback machine
                  response = requests.post(api_base_url, headers=headers, data={'url': page})
                  # Check the status code of the response
                  if response.status_code == 200:
                      print(f'Successfully saved {page} to the Wayback machine')
                      writer.writerow({'url': page, 'status': 'success'})
                  else:
                      print(f'Error saving {page} to the Wayback machine')
                      writer.writerow({'url': page, 'status': 'error', 'error_code': response.status_code})
                  # Add a delay of 20 seconds before the next iteration
                  time.sleep(20)
          EOF
                   
      - name: Commit log file and log file with timestamp
        run: |
          timestamp=$(date +%Y-%m-%d__%H-%M-%S)
          git config --local user.email "analphabit@gmail.com"
          git config --local user.name "analphabit"
          cp saving_logs/log.csv saving_logs/log_${timestamp}.csv
          git add saving_logs/log.csv saving_logs/log_${timestamp}.csv
          git commit -m "Add log files with timestamp ${timestamp}"
          git push
